@echo off
REM GitHub Access Checker Startup Script
REM Generated by AiPy
echo Starting GitHub Access Checker...
echo.
python github_checker.py
if %errorlevel% neq 0 (
    echo.
    echo Error: Python execution failed!
    echo Please ensure Python is installed and added to PATH.
    echo.
    pause
)